name: Google Cloud Run Build & Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build & Publish
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.co.*/\1/')
        docker build -t gcr.io/${PROJECT_ID}/insight-cleaner1 .
        docker push gcr.io/${PROJECT_ID}/insight-cleaner1

    - name: Deploy
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.co.*/\1/')
        gcloud run deploy insight-cleaner --image gcr.io/${PROJECT_ID}/insight-cleaner1 \
        --project ${PROJECT_ID} \
        --service-account cloud-run-insight-cleaner@${PROJECT_ID}.iam.gserviceaccount.com \
        --region europe-west1 \
        --platform managed \
        --allow-unauthenticated \
        --no-allow-unauthenticated
