name: Google Cloud Run Build & Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build & Publish
      run: |
        docker build -t gcr.io/x-i-a-test/insight-cleaner .
        docker push gcr.io/x-i-a-test/insight-cleaner

    - name: Use gcloud CLI
      run: gcloud info
